export enum locationValues {
  STATE = 'State',
  COUNTRY = 'Country',
}

const removeAccents = (str: string) => str.normalize('NFD').replace(/[\u0300-\u036f]/g, '');

const statePatterns: { [key: string]: RegExp } = {
  AC: /\b(Acre|AC)\b/i,
  AL: /\b(Alagoas|AL)\b/i,
  AP: /\b(Amapa|AP)\b/i,
  AM: /\b(Amazonas|AM)\b/i,
  BA: /\b(Bahia|BA)\b/i,
  CE: /\b(Ceara|CE)\b/i,
  DF: /\b(Distrito[_\-\\s]Federal|DF)\b/i,
  ES: /\b(Espirito[_\-\\s]Santo|ES)\b/i,
  GO: /\b(Goias|GO)\b/i,
  MA: /\b(Maranhao|MA)\b/i,
  MT: /\b(Mato[_\-\\s]Grosso|MT)\b/i,
  MS: /\b(Mato[_\-\\s]Grosso[_\-\\s]do[_\-\\s]Sul|MS)\b/i,
  MG: /\b(Minas[_\-\\s]Gerais|MG)\b/i,
  PA: /\b(Para|PA)\b/i,
  PB: /\b(Paraiba|PB)\b/i,
  PR: /\b(Parana|PR)\b/i,
  PE: /\b(Pernambuco|PE)\b/i,
  PI: /\b(Piaui|PI)\b/i,
  RJ: /\b(Rio[_\-\\s]De[_\-\\s]Janeiro|RJ)\b/i,
  RN: /\b(Rio[_\-\\s]Grande[_\-\\s]Do[_\-\\s]Norte|RN)\b/i,
  RS: /\b(Rio[_\-\\s]Grande[_\-\\s]Do[_\-\\s]Sul|RS)\b/i,
  RO: /\b(Rondonia|RO)\b/i,
  RR: /\b(Roraima|RR)\b/i,
  SC: /\b(Santa[_\-\\s]Catarina|SC)\b/i,
  SP: /\b(Sao[_\-\\s]Paulo|SP)\b/i,
  SE: /\b(Sergipe|SE)\b/i,
  TO: /\b(Tocantins|TO)\b/i,
};

const countryPatterns: { [key: string]: RegExp } = {
  Afeganistão: /\b(Afghanistan|AFG|Afeganistao)\b/i,
  'África do Sul': /\b(South[_\-\\s]Africa|ZAF|Africa[_\-\\s]do[_\-\\s]Sul)\b/i,
  Albânia: /\b(Albania|ALB|Albania)\b/i,
  Alemanha: /\b(Germany|GER|Alemanha)\b/i,
  Andorra: /\b(Andorra|AND)\b/i,
  Angola: /\b(Angola|AGO|Angola)\b/i,
  'Antígua e Barbuda': /\b(Antigua[_\-\\s]and[_\-\\s]Barbuda|ATG|Antigua[_\-\\s]e[_\-\\s]Barbuda)\b/i,
  'Arábia Saudita': /\b(Saudi[_\-\\s]Arabia|SAU|Arabia[_\-\\s]Saudita)\b/i,
  Argélia: /\b(Algeria|DZA|Argelia)\b/i,
  Argentina: /\b(Argentina|ARG)\b/i,
  Armênia: /\b(Armenia|ARM)\b/i,
  Austrália: /\b(Australia|AUS)\b/i,
  Áustria: /\b(Austria|AUT)\b/i,
  Azerbaijão: /\b(Azerbaijan|AZE|Azerbaijao)\b/i,
  Bahamas: /\b(Bahamas|BHS)\b/i,
  Bahrein: /\b(Bahrain|BHR|Bahrein)\b/i,
  Bangladesh: /\b(Bangladesh|BGD)\b/i,
  Barbados: /\b(Barbados|BRB)\b/i,
  Belarus: /\b(Belarus|BLR)\b/i,
  Bélgica: /\b(Belgium|BEL|Belgica)\b/i,
  Belize: /\b(Belize|BLZ|Belize)\b/i,
  Benin: /\b(Benin|BEN|Benin)\b/i,
  Butão: /\b(Bhutan|BTN|Butao)\b/i,
  Bolívia: /\b(Bolivia|BOL|Bolivia)\b/i,
  'Bósnia e Herzegovina': /\b(Bosnia[_\-\\s]and[_\-\\s]Herzegovina|BIH|Bosnia[_\-\\s]e[_\-\\s]Hercegovina)\b/i,
  Botsuana: /\b(Botswana|BWA|Botsuana)\b/i,
  Brasil: /\b(Brazil|BRA|Brasil)\b/i,
  Brunei: /\b(Brunei|BRN)\b/i,
  Bulgária: /\b(Bulgaria|BGR)\b/i,
  'Burkina Faso': /\b(Burkina[_\-\\s]Faso|BFA)\b/i,
  Burundi: /\b(Burundi|BDI)\b/i,
  'Cabo Verde': /\b(Cabo[_\-\\s]Verde|CPV)\b/i,
  Camboja: /\b(Cambodia|KHM|Camboja)\b/i,
  Camarões: /\b(Cameroon|CMR|Camaroes)\b/i,
  Canadá: /\b(Canada|CAN)\b/i,
  Catar: /\b(Qatar|QAT|Catar)\b/i,
  Cazaquistão: /\b(Kazakhstan|KAZ|Cazaquistao)\b/i,
  Chade: /\b(Chad|TCD|Chade)\b/i,
  Chile: /\b(Chile|CHL)\b/i,
  China: /\b(China|CHN)\b/i,
  Chipre: /\b(Cyprus|CYP|Chipre)\b/i,
  Colômbia: /\b(Colombia|COL)\b/i,
  Comores: /\b(Comoros|COM|Comores)\b/i,
  'Coreia do Norte': /\b(North Korea|PRK|Coreia[_\-\\s]do[_\-\\s]Norte)\b/i,
  'Coreia do Sul': /\b(South[_\-\\s]Korea|KOR|Coreia[_\-\\s]do[_\-\\s]Sul)\b/i,
  'Costa do Marfim': /\b(Cote[_\-\\s]dIvoire|CIV|Costa[_\-\\s]do[_\-\\s]Marfim)\b/i,
  'Costa Rica': /\b(Costa[_\-\\s]Rica|CRI)\b/i,
  Croácia: /\b(Croatia|HRV|Croacia)\b/i,
  Cuba: /\b(Cuba|CUB)\b/i,
  Dinamarca: /\b(Denmark|DNK|Dinamarca)\b/i,
  Djibuti: /\b(Djibouti|DJI|Djibuti)\b/i,
  Dominica: /\b(Dominica|DMA|Dominica)\b/i,
  Egito: /\b(Egypt|EGY|Egito)\b/i,
  'El Salvador': /\b(El[_\-\\s]Salvador|SLV)\b/i,
  'Emirados Árabes Unidos': /\b(United[_\-\\s]Arab[_\-\\s]Emirates|ARE|Emirados[_\-\\s]Arabes[_\-\\s]Unidos)\b/i,
  Equador: /\b(Ecuador|ECU|Equador)\b/i,
  Eritreia: /\b(Eritrea|ERI|Eritreia)\b/i,
  Eslováquia: /\b(Slovakia|SVK|Eslovaquia)\b/i,
  Eslovênia: /\b(Slovenia|SVN|Eslovenia)\b/i,
  Espanha: /\b(Spain|ESP|Espanha)\b/i,
  EUA: /\b(United[_\-\\s]States|USA|US|EUA)\b/i,
  Estônia: /\b(Estonia|EST)\b/i,
  Eswatini: /\b(Eswatini|SWZ)\b/i,
  Etiópia: /\b(Ethiopia|ETH|Etiopia)\b/i,
  Fiji: /\b(Fiji|FJI)\b/i,
  Filipinas: /\b(Philippines|PHL|Filipinas)\b/i,
  Finlândia: /\b(Finland|FIN|Finlandia)\b/i,
  França: /\b(France|FRA|Franca)\b/i,
  Gabão: /\b(Gabon|GAB|Gabao)\b/i,
  Gâmbia: /\b(Gambia|GMB)\b/i,
  Gana: /\b(Ghana|GHA|Gana)\b/i,
  Geórgia: /\b(Georgia|GEO)\b/i,
  Granada: /\b(Grenada|GRD|Granada)\b/i,
  Grécia: /\b(Greece|GRC|Grecia)\b/i,
  Guatemala: /\b(Guatemala|GTM)\b/i,
  Guiana: /\b(Guyana|GUY|Guiana)\b/i,
  Guiné: /\b(Guinea|GIN|Guine)\b/i,
  'Guiné-Bissau': /\b(Guinea-Bissau|GNB|Guine-Bissau)\b/i,
  'Guiné Equatorial': /\b(Equatorial[_\-\\s]Guinea|GNQ|Guine[_\-\\s]Equatorial)\b/i,
  Haiti: /\b(Haiti|HTI)\b/i,
  Holanda: /\b(Netherlands|NLD|Holanda)\b/i,
  Honduras: /\b(Honduras|HND)\b/i,
  Hungria: /\b(Hungary|HUN|Hungria)\b/i,
  Iémen: /\b(Yemen|YEM|Iemen)\b/i,
  'Ilhas Marshall': /\b(Marshall[_\-\\s]Islands|MHL|Ilhas[_\-\\s]Marshall)\b/i,
  'Ilhas Salomão': /\b(Solomon[_\-\\s]Islands|SLB|Ilhas[_\-\\s]Salomao)\b/i,
  Índia: /\b(India|IND)\b/i,
  Indonésia: /\b(Indonesia|IDN)\b/i,
  Irã: /\b(Iran|IRN|Ira)\b/i,
  Iraque: /\b(Iraq|IRQ|Iraque)\b/i,
  Irlanda: /\b(Ireland|IRL|Irlanda)\b/i,
  Islândia: /\b(Iceland|ISL|Islândia)\b/i,
  Israel: /\b(Israel|ISR)\b/i,
  Itália: /\b(Italy|ITA|Italia)\b/i,
  Jamaica: /\b(Jamaica|JAM)\b/i,
  Japão: /\b(Japan|JPN|Japao)\b/i,
  Jordânia: /\b(Jordan|JOR|Jordania)\b/i,
  Kiribati: /\b(Kiribati|KIR)\b/i,
  Kuwait: /\b(Kuwait|KWT)\b/i,
  Laos: /\b(Laos|LAO)\b/i,
  Lesoto: /\b(Lesotho|LSO|Lesoto)\b/i,
  Letônia: /\b(Latvia|LVA|Letonia)\b/i,
  Líbano: /\b(Lebanon|LBN|Libano)\b/i,
  Libéria: /\b(Liberia|LBR)\b/i,
  Líbia: /\b(Libya|LBY|Libia)\b/i,
  Liechtenstein: /\b(Liechtenstein|LIE)\b/i,
  Lituânia: /\b(Lithuania|LTU|Lituania)\b/i,
  Luxemburgo: /\b(Luxembourg|LUX|Luxemburgo)\b/i,
  Madagascar: /\b(Madagascar|MDG)\b/i,
  Malásia: /\b(Malaysia|MYS|Malasia)\b/i,
  Malawi: /\b(Malawi|MWI)\b/i,
  Maldivas: /\b(Maldives|MDV)\b/i,
  Mali: /\b(Mali|MLI)\b/i,
  Malta: /\b(Malta|MLT)\b/i,
  Marrocos: /\b(Morocco|MAR|Marrocos)\b/i,
  Mauritânia: /\b(Mauritania|MRT)\b/i,
  Maurício: /\b(Mauritius|MUS|Mauricio)\b/i,
  México: /\b(Mexico|MEX)\b/i,
  Mianmar: /\b(Myanmar|MMR|Mianmar)\b/i,
  Micronésia: /\b(Micronesia|FSM)\b/i,
  Moçambique: /\b(Mozambique|MOZ|Mocambique)\b/i,
  Moldávia: /\b(Moldova|MDA|Moldavia)\b/i,
  Mônaco: /\b(Monaco|MCO)\b/i,
  Mongólia: /\b(Mongolia|MNG)\b/i,
  Montenegro: /\b(Montenegro|MNE)\b/i,
  Namíbia: /\b(Namibia|NAM)\b/i,
  Nauru: /\b(Nauru|NRU)\b/i,
  Nepal: /\b(Nepal|NPL)\b/i,
  Nicarágua: /\b(Nicaragua|NIC)\b/i,
  Níger: /\b(Niger|NER)\b/i,
  Nigéria: /\b(Nigeria|NGA)\b/i,
  Noruega: /\b(Norway|NOR|Noruega)\b/i,
  'Nova Zelândia': /\b(New[_\-\\s]Zealand|NZL|Nova[_\-\\s]Zelandia)\b/i,
  Omã: /\b(Oman|OMN|Oma)\b/i,
  Palau: /\b(Palau|PLW)\b/i,
  Panamá: /\b(Panama|PAN)\b/i,
  'Papua Nova Guiné': /\b(Papua[_\-\\s]New[_\-\\s]Guinea|PNG|Papua[_\-\\s]Nova[_\-\\s]Guine)\b/i,
  Paquistão: /\b(Pakistan|PAK|Paquistao)\b/i,
  Paraguai: /\b(Paraguay|PRY|Paraguai)\b/i,
  Peru: /\b(Peru|PER)\b/i,
  Polônia: /\b(Poland|POL|Polonia)\b/i,
  Portugal: /\b(Portugal|PRT)\b/i,
  Quênia: /\b(Kenya|KEN|Quenia)\b/i,
  Quirguistão: /\b(Kyrgyzstan|KGZ|Quirguistao)\b/i,
  'Reino Unido': /\b(United[_\-\\s]Kingdom|GBR|Reino[_\-\\s]Unido)\b/i,
  'República Centro-Africana': /\b(Central[_\-\\s]African[_\-\\s]Republic|CAF|Republica[_\-\\s]Centro[_\-\\s]Africana)\b/i,
  'República Checa': /\b(Czech[_\-\\s]Republic|CZE|Republica[_\-\\s]Checa)\b/i,
  'República Democrática do Congo':
    /\b(Democratic[_\-\\s]Republic[_\-\\s]of[_\-\\s]the[_\-\\s]Congo|COD|Republica[_\-\\s]Democratica[_\-\\s]do[_\-\\s]Congo)\b/i,
  'República do Congo': /\b(Republic[_\-\\s]of[_\-\\s]the[_\-\\s]Congo|COG|Republica[_\-\\s]do[_\-\\s]Congo)\b/i,
  'República Dominicana': /\b(Dominican[_\-\\s]Republic|DOM|Republica[_\-\\s]Dominicana)\b/i,
  Romênia: /\b(Romania|ROU|Romenia)\b/i,
  Ruanda: /\b(Rwanda|RWA|Ruanda)\b/i,
  Rússia: /\b(Russia|RUS)\b/i,
  Samoa: /\b(Samoa|WSM|Samoa)\b/i,
  'San Marino': /\b(San[_\-\\s]Marino|SMR|Sao[_\-\\s]Marino)\b/i,
  'Santa Lúcia': /\b(Saint[_\-\\s]Lucia|LCA|Santa[_\-\\s]Lucia)\b/i,
  'São Cristóvão e Nevis': /\b(Saint[_\-\\s]Kitts[_\-\\s]and[_\-\\s]Nevis|KNA|Sao[_\-\\s]Cristovao[_\-\\s]e[_\-\\s]Nevis)\b/i,
  'São Tomé e Príncipe': /\b(Sao[_\-\\s]Tome[_\-\\s]and[_\-\\s]Principe|STP|Sao[_\-\\s]Tome[_\-\\s]e[_\-\\s]Principe)\b/i,
  'São Vicente e Granadinas': /\b(Saint[_\-\\s]Vincent[_\-\\s]and[_\-\\s]the[_\-\\s]Grenadines|VCT|Sao[_\-\\s]Vicente[_\-\\s]e[_\-\\s]Granadinas)\b/i,
  Senegal: /\b(Senegal|SEN)\b/i,
  'Serra Leoa': /\b(Sierra[_\-\\s]Leone|SLE|Serra[_\-\\s]Leoa)\b/i,
  Sérvia: /\b(Serbia|SRB|Servia)\b/i,
  Seychelles: /\b(Seychelles|SYC|Seicheles)\b/i,
  Singapura: /\b(Singapore|SGP|Singapura)\b/i,
  Síria: /\b(Syria|SYR|Siria)\b/i,
  Somália: /\b(Somalia|SOM)\b/i,
  'Sri Lanka': /\b(Sri[_\-\\s]Lanka|LKA)\b/i,
  Sudão: /\b(Sudan|SDN|Sudao)\b/i,
  'Sudão do Sul': /\b(South[_\-\\s]Sudan|SSD|Sudao[_\-\\s]do[_\-\\s]Sul)\b/i,
  Suécia: /\b(Sweden|SWE|Suecia)\b/i,
  Suíça: /\b(Switzerland|CHE|Suica)\b/i,
  Suriname: /\b(Suriname|SUR)\b/i,
  Tailândia: /\b(Thailand|THA|Tailandia)\b/i,
  Tajiquistão: /\b(Tajikistan|TJK|Tajiquistao)\b/i,
  Tanzânia: /\b(Tanzania|TZA)\b/i,
  'Timor-Leste': /\b(East-Timor|TLS|Timor-Leste)\b/i,
  Togo: /\b(Togo|TGO)\b/i,
  Tonga: /\b(Tonga|TON)\b/i,
  'Trindade e Tobago': /\b(Trinidad[_\-\\s]and[_\-\\s]Tobago|TTO|Trindade[_\-\\s]e[_\-\\s]Tobago)\b/i,
  Tunísia: /\b(Tunisia|TUN)\b/i,
  Turcomenistão: /\b(Turkmenistan|TKM|Turcomenistao)\b/i,
  Turquia: /\b(Turkey|TUR|Turquia)\b/i,
  Tuvalu: /\b(Tuvalu|TUV)\b/i,
  Ucrânia: /\b(Ukraine|UKR|Ucrania)\b/i,
  Uganda: /\b(Uganda|UGA)\b/i,
  Uruguai: /\b(Uruguay|URY|Uruguai)\b/i,
  Uzbequistão: /\b(Uzbekistan|UZB|Uzbequistao)\b/i,
  Vanuatu: /\b(Vanuatu|VUT)\b/i,
  Vaticano: /\b(Vatican City|VAT|Vaticano)\b/i,
  Venezuela: /\b(Venezuela|VEN)\b/i,
  Vietnã: /\b(Vietnam|VNM|Vietna)\b/i,
  Zâmbia: /\b(Zambia|ZMB)\b/i,
  Zimbábue: /\b(Zimbabwe|ZWE|Zimbabue)\b/i,
};

export const normalizeLocationNames = (locationInput: string, locationType: locationValues): string => {
  for (const [locationName, regex] of Object.entries(locationType === locationValues.COUNTRY ? countryPatterns : statePatterns)) {
    if (regex.test(removeAccents(locationInput))) {
      return locationName;
    }
  }
  return locationInput;
};
